### ISSUE TITLE
Wrong Git Flow

### ISSUE THREAD

**Issue by quochung-cyou** [NgNhatThanh/NotMobsInc---LibGDXgame#5]
Các em xem lại luồng mình tạo nhánh và merge cho đúng nhé, cứ push thẳng develop như hiện tại thì sau mà code nó bắt đầu chồng lấn vào nhau là fix mệt lắm đấy

@gxdumplingg @NgNhatThanh @DoangVan411 

các em xem lại của các bạn khác (vd nhóm 1) rồi làm lại từ những cái sau nhé, sau close cái issues này

**Comment by NgNhatThanh** [comment]
Vâng bọn em đã sắp xếp lại các nhánh và sẽ chú ý hơn ạ
